workflows:
  android-compose-app:
    name: Build Android Compose App
    max_build_duration: 60
    environment:
      groups:
        - android_credentials # Opcional, para assinar o APK
      java: 17
      node: 20 # Útil para outros scripts, mesmo em Android
    scripts:
      - name: Configurar Ambiente Android
        script: |
          echo "Configurando SDKMAN! e Java..."
          sudo apt-get update
          sudo apt-get install --yes unzip zip
          sdkmanager "cmake;3.22.1" # Pode ser necessário para algumas dependências nativas

      - name: Listar Estrutura do Projeto
        script: |
          echo "Diretório de trabalho: $PWD"
          echo "Estrutura do projeto:"
          find . -name '*.gradle' -o -name '*.kt' -o -name '*.xml' -o -name '*.yaml' -o -name 'gradlew' | head -20
          echo "... e mais."

      - name: Dar Permissões e Configurar Gradle
        script: |
          chmod +x ./gradlew
          # Configuração para evitar problemas de memory lock no CI
          echo "org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "android.nonFinalResIds=false" >> gradle.properties # Suprime avisos para projetos não finalizados

      - name: Build e Teste com Gradle Wrapper
        script: |
          ./gradlew clean assembleDebug --stacktrace --no-daemon --warning-mode=all
        timeout: 1800

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/output.json
      - app/build/reports/**/*

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
