workflows:
  android-app:
    name: Build Android App
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: 🔍 DEBUG - Verificar estrutura do repositório
        script: |
          echo "=========================================="
          echo "DEBUG: ESTRUTURA COMPLETA DO REPOSITÓRIO"
          echo "=========================================="
          echo "Diretório atual: $PWD"
          echo "------------------------------------------"
          echo "LISTANDO TODOS OS ARQUIVOS E PASTAS:"
          ls -la
          echo "------------------------------------------"
          echo "PROCURANDO POR ARQUIVOS GRADLE:"
          find . -name "*.gradle" -type f 2>/dev/null || echo "Nenhum arquivo .gradle encontrado"
          echo "------------------------------------------"
          echo "PROCURANDO POR ARQUIVOS KOTLIN:"
          find . -name "*.kt" -type f | head -5
          echo "------------------------------------------"
          echo "PROCURANDO POR PASTA APP:"
          find . -name "app" -type d
          echo "=========================================="
          
      - name: Definir permissões do Gradle Wrapper
        script: |
          chmod +x gradlew
      - name: Limpar projeto
        script: ./gradlew clean --stacktrace --info
      - name: Construir APK de Depuração
        script: ./gradlew assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
