workflows:
  android-app:
    name: Build Android App
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Clonar repositório e verificar
        script: |
          echo "Diretório inicial: $PWD"
          ls -la
          rm -rf .
          git clone --branch main https://github.com/Gabrielphnz/Projeto-de-estoque-.git .
          echo "Diretório após clonagem: $PWD"
          ls -la
      - name: Definir permissões do Gradle Wrapper
        script: chmod +x gradlew
      - name: Limpar projeto
        script: ./gradlew clean --stacktrace --info
      - name: Construir APK de Depuração
        script: ./gradlew assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
