workflows:
  android-app:
    name: Build Android App
    max_build_duration: 30
    environment:
      android: latest
      java: 17
    scripts:
      - name: Navegar para diretório do projeto
        script: |
          echo "Diretório atual: $PWD"
          cd GerenciadorEstoqueFull
          echo "Navegando para: $PWD"
          echo "Verificando arquivos do projeto:"
          ls -la *.gradle
          
      - name: Verificar estrutura do projeto Android
        script: |
          echo "Estrutura do projeto Android:"
          ls -la
          echo "Pasta app:"
          ls -la app/
          
      - name: Corrigir nome do settings.gradle se necessário
        script: |
          if [ -f "Settings.gradle" ] && [ ! -f "settings.gradle" ]; then
            echo "Corrigindo Settings.gradle → settings.gradle"
            mv Settings.gradle settings.gradle
          fi
          
      - name: Definir permissões do Gradle Wrapper
        script: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            echo "✅ gradlew tornando executável"
          else
            echo "⚠️  gradlew não encontrado, usando gradle do sistema"
          fi
          
      - name: Limpar projeto
        script: |
          if [ -f "gradlew" ]; then
            ./gradlew clean --stacktrace --info
          else
            gradle clean --stacktrace --info
          fi
          
      - name: Construir APK de Depuração
        script: |
          if [ -f "gradlew" ]; then
            ./gradlew assembleDebug --stacktrace --info
          else
            gradle assembleDebug --stacktrace --info
          fi
          
    artifacts:
      - GerenciadorEstoqueFull/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
