workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Clean project
        script: gradle clean

      - name: Assemble Debug APK
        script: gradle assembleDebug

      - name: Assemble Release APK
        script: gradle assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - gabrielphnz@gmail.com
