workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Go to project folder
        script: cd GerenciadorEstoqueFull

      - name: Clean project
        script: cd GerenciadorEstoqueFull && gradle clean

      - name: Assemble Debug APK
        script: cd GerenciadorEstoqueFull && gradle assembleDebug

      - name: Assemble Release APK
        script: cd GerenciadorEstoqueFull && gradle assembleRelease

    artifacts:
      - GerenciadorEstoqueFull/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com