workflows:
  android-app:
    name: Build Android App
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Clonar repositório manualmente
        script: |
          rm -rf /Users/builder/clone/*
          git clone https://github.com/Gabrielphnz/Projeto-de-estoque-.git .
          ls -la
      - name: Definir permissões do Gradle Wrapper
        script: chmod +x gradlew
      - name: Limpar projeto
        script: ./gradlew clean
      - name: Construir APK de Depuração
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
