workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    environment:
      java: 17         # versão do Java
    scripts:
      - name: Clean project
        script: ./gradlew clean

      - name: Assemble Debug APK
        script: ./gradlew assembleDebug

      - name: Assemble Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - gabrielphnz@gmail.com
