workflows:
  android-app:
    name: Build Android App
    max_build_duration: 30
    environment:
      java: 17
      vars:
        GRADLE_VERSION: "8.14.1"
        GITHUB_REPO_URL: "https://$GITHUB_TOKEN@github.com/Gabrielphnz/Projeto-de-estoque-.git"
    scripts:
      - name: Verificar e clonar repositório manualmente
        script: |
          echo "Diretório inicial: $PWD"
          ls -la
          rm -rf .
          git clone --branch main $GITHUB_REPO_URL .
          echo "Diretório após clonagem: $PWD"
          ls -la
      - name: Definir permissões do Gradle Wrapper (fallback)
        script: |
          if [ -f gradlew ]; then
            chmod +x gradlew
          else
            echo "Gradle Wrapper não encontrado. Instalando Gradle global."
            wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
            unzip gradle-$GRADLE_VERSION-bin.zip
            export PATH=$PATH:$PWD/gradle-$GRADLE_VERSION/bin
            gradle --version
          fi
      - name: Limpar projeto
        script: |
          if [ -f gradlew ]; then
            ./gradlew clean --stacktrace --info
          else
            gradle clean --stacktrace --info
          fi
      - name: Construir APK de Depuração
        script: |
          if [ -f gradlew ]; then
            ./gradlew assembleDebug --stacktrace --info
          else
            gradle assembleDebug --stacktrace --info
          fi
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
