workflows:
  android-app:
    name: Build Android App
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Listar conteúdo do diretório
        script: ls -la
      - name: Limpar projeto
        script: ./gradlew clean
      - name: Construir APK de Depuração
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
